### ISSUE TITLE
Unable to load components module

### ISSUE THREAD

**Issue by rudedogg** [sheshbabu/rustmart-yew-example#2]
Hi, thanks for the blog post and example, it looks really interesting. I'm new to rust and trying to follow along, but stuck.

I am at the "Splitting into reusable components" step, where `product_card.rs` is created. It seems that cargo can't find my new `components` module/namespace? 

Here is the error I'm getting:

```shell
error[E0432]: unresolved import `crate::components`
 --> src/pages/home.rs:2:12
  |
2 | use crate::components::ProductCard;
  |            ^^^^^^^^^^ maybe a missing crate `components`?
```

I've uploaded my code here if anyone has time to take a look:
https://github.com/rudedogg/rustmart

Thanks

**Comment by sheshbabu** [comment]
Hi, you need to include the `components` module in `lib.rs` - https://github.com/sheshbabu/rustmart-yew-example/blob/master/src/lib.rs#L3. It seems I've missed it in that section, will update it 👍

Here's an introduction to Rust's module system - http://www.sheshbabu.com/posts/rust-module-system 😊

**Comment by rudedogg** [comment]
Thanks so much!

**Comment by sheshbabu** [comment]
@rudedogg I've fixed this in the blog post - https://github.com/sheshbabu/Blog/commit/279b1cb311615d1e6311a49c43b1c434ef44eef9 

Thanks for noticing this! 😊
