### ISSUE TITLE
Routing headache

### ISSUE THREAD

**Issue by ddalcino** [sheshbabu/rustmart-yew-example#3]
Hi! I'm really enjoying your tutorial so far, but I had a little trouble following the routing section, and I thought I'd let you know what went wrong so that no one else has the same issue that I did.

When you added the route `/product/{id}` that links to the ProductDetailPage, it did not occur to me that the new route has to be written before the `/` route. I had my `/` route written first, and then `/product/{id}` afterward. It took me a long time to realize that this order causes the `/` route to match all GET requests. In retrospect, it makes perfect sense that this would be the case, but I think that it would be really helpful for the tutorial to have a note that warns about this.

~~I can file a PR if you think that would be helpful.~~ Whoops ... didn't realize the tutorial is actually in your blog, and not this repo. I don't think I should be writing PRs for someone else's blog.

**Comment by sheshbabu** [comment]
Hi @ddalcino, thanks for bringing this to attention. I've fixed the post as you suggested - https://github.com/sheshbabu/Blog/commit/4ee2789037f7144a8bdeac0c8d16e01494a9985e 😊

Cheers,
Shesh
