### ISSUE TITLE
Permission to reuse?

### ISSUE THREAD

**Issue by aclueless** [sheshbabu/rustmart-yew-example#4]
Hi @sheshbabu,

I want to port this example to https://github.com/aclueless/spair to see how it feel, to find and fix problems in it.... but there is no license in this repo. I read elsewhere that if there is no license, I can not reuse anything in this repo.

So, I open this to ask for your permission to reuse items in this repo to port this example to Spair.

*I am sorry that my English skill is not good enough to write this message in an appropriate/correct style. Hope it causes no issues :grinning:*

Best regards,

aclueless

**Comment by sheshbabu** [comment]
Hey @aclueless, please feel free to reuse the code 👍

**Comment by aclueless** [comment]
Yeah, thank you very much!
